# Generated by Django 3.0.3 on 2020-02-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flightinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(blank=True, max_length=100, null=True)),
                ('airline', models.CharField(blank=True, max_length=45, null=True)),
                ('destinations', models.CharField(blank=True, max_length=45, null=True)),
                ('flightnumbers', models.TextField(blank=True, db_column='flightNumbers', null=True)),
                ('scheduledtime', models.CharField(blank=True, db_column='scheduledTime', max_length=45, null=True)),
                ('estimatedtime', models.CharField(blank=True, db_column='estimatedTime', max_length=45, null=True)),
                ('scheduleddate', models.CharField(blank=True, db_column='scheduledDate', max_length=45, null=True)),
                ('latesttime', models.CharField(blank=True, db_column='latestTime', max_length=45, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('statuscolor', models.CharField(blank=True, db_column='statusColor', max_length=45, null=True)),
                ('origin', models.CharField(blank=True, max_length=45, null=True)),
                ('gate', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'flightinfo',
                'managed': False,
            },
        ),
    ]
