# Generated by Django 2.2.3 on 2020-03-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flightinfo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('airline', models.CharField(blank=True, max_length=45, null=True)),
                ('destinations', models.CharField(blank=True, max_length=45, null=True)),
                ('flightnumbers', models.TextField(blank=True, db_column='flightNumbers', null=True)),
                ('scheduledtime', models.CharField(blank=True, db_column='scheduledTime', max_length=45, null=True)),
                ('estimatedtime', models.CharField(blank=True, db_column='estimatedTime', max_length=45, null=True)),
                ('scheduleddate', models.CharField(blank=True, db_column='scheduledDate', max_length=45, null=True)),
                ('latesttime', models.CharField(blank=True, db_column='latestTime', max_length=45, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('statuscolor', models.CharField(blank=True, db_column='statusColor', max_length=45, null=True)),
                ('origin', models.CharField(blank=True, max_length=45, null=True)),
                ('gate', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
